INSERT INTO books(book_name, num_of_chapts, testament) VALUES
('Matthew', 28, 'New'),
('Mark', 16, 'New'),
('Luke', 24, 'New'),
('John', 21, 'New'),
('Acts', 28, 'New'),
('Romans', 16, 'New'),
('1 Corinthians', 16, 'New'),
('2 Corinthians', 13, 'New'),
('Galatians', 6, 'New'),
('Ephesians', 6, 'New'),
('Philippians', 4, 'New'),
('Colossians', 4, 'New'),
('1 Thessalonians', 5, 'New'),
('2 Thessalonians', 3, 'New'),
('1 Timothy', 6, 'New'),
('2 Timothy', 4, 'New'),
('Titus', 3, 'New'),
('Philemon', 1, 'New'),
('Hebrews', 13, 'New'),
('James', 5, 'New'),
('1 Peter', 5, 'New'),
('2 Peter', 3, 'New'),
('1 John', 5, 'New'),
('2 John', 1, 'New'),
('3 John', 1, 'New'),
('Jude', 1, 'New'),
('Revelation', 22, 'New');