INSERT INTO books(book_name, num_of_chapts) VALUES
('Matthew', 28),
('Mark', 16),
('Luke', 24),
('John', 21),
('Acts', 28),
('Romans', 16),
('1 Corinthians', 16),
('2 Corinthians', 13),
('Galatians', 6),
('Ephesians', 6),
('Philippians', 4),
('Colossians', 4),
('1 Thessalonians', 5),
('2 Thessalonians', 3),
('1 Timothy', 6),
('2 Timothy', 4),
('Titus', 3),
('Philemon', 1),
('Hebrews', 13),
('James', 5),
('1 Peter', 5),
('2 Peter', 3),
('1 John', 5),
('2 John', 1),
('3 John', 1),
('Jude', 1),
('Revelation', 22);